package com.wiwit.util;

public class StaticData {
	public static String str = ""
			+ "abduct@_@menculik@_@false@_@false@-@"
			+ "abhor@_@tidak menyukai@_@false@_@false@-@"
			+ "abominable@_@buruk sekali@_@false@_@false@-@"
			+ "abreviation@_@singkatan, kependekan@_@false@_@false@-@"
			+ "abroad@_@di luar negeri@_@true@_@false@-@"
			+ "absurd@_@mustahil, tak masuk akal@_@false@_@false@-@"
			+ "accede@_@mengabulkan@_@true@_@false@-@"
			+ "accomplish@_@menyelesaikan@_@false@_@false@-@"
			+ "accord@_@persetujuan@_@false@_@false@-@"
			+ "accuse@_@menuduh@_@false@_@false@-@"
			+ "achieved@_@mencapai@_@false@_@true@-@"
			+ "acquaintance@_@kenalan@_@false@_@true@-@"
			+ "acquire@_@memperoleh@_@false@_@false@-@"
			+ "adhesive@_@perekat, bahan perekat@_@false@_@true@-@"
			+ "admire@_@mengagumi@_@false@_@true@-@"
			+ "admission@_@izin/karcis masuk@_@true@_@false@-@"
			+ "admonition@_@peringatan@_@true@_@false@-@"
			+ "adore@_@memuja@_@true@_@false@-@"
			+ "adultery@_@perzinaan@_@false@_@true@-@"
			+ "advent@_@kedatangan@_@true@_@false@-@"
			+ "adversary@_@musuh, lawan@_@false@_@false@-@"
			+ "adverse@_@merugikan@_@true@_@false@-@"
			+ "adviser@_@penasehat@_@false@_@true@-@"
			+ "affable@_@ramah tamah, baik hati@_@true@_@false@-@"
			+ "affair@_@urusan, peristiwa, hubungan gelap@_@false@_@true@-@"
			+ "affirm@_@menegaskan@_@false@_@false@-@"
			+ "afford@_@menghasilkan, mampu, memberi@_@false@_@false@-@"
			+ "against@_@melawan, menentang@_@false@_@true@-@"
			+ "aggravate@_@menjengkelkan, menyakiti@_@true@_@false@-@"
			+ "agile@_@tangkas@_@false@_@true@-@"
			+ "agitate@_@mengganggu, menggoncangkan@_@true@_@false@-@"
			+ "agony@_@kesakitan@_@true@_@false@-@"
			+ "alas@_@aduh(menyatakan kesusahan)@_@true@_@false@-@"
			+ "alcove@_@ruangan kecil dalam kamar@_@false@_@true@-@"
			+ "alertness@_@kewaspadaan@_@false@_@true@-@"
			+ "alloy@_@(logam) campuran@_@true@_@false@-@"
			+ "allure@_@daya tarik@_@false@_@true@-@"
			+ "aloe@_@pohon gaharu@_@true@_@false@-@"
			+ "along@_@berhubungan baik, bergaul baik@_@false@_@true@-@"
			+ "altered@_@mengubah@_@false@_@false@-@"
			+ "although@_@walaupun, meskipun@_@false@_@true@-@"
			+ "ambidextrous@_@sangat pandai, sangat tangkas@_@false@_@false@-@"
			+ "among@_@diantara@_@true@_@false@-@"
			+ "amuse@_@membuat orang tertawa, , menarik perhatian@_@false@_@true@-@"
			+ "anaesthetic@_@obat bius@_@false@_@false@-@"
			+ "ancestor@_@leluhur@_@false@_@false@-@"
			+ "ancestral@_@keturunan leluhur@_@false@_@false@-@"
			+ "anguish@_@kesedihan yg mendalam@_@false@_@true@-@"
			+ "annihilate@_@menghancurkan@_@false@_@true@-@"
			+ "announce@_@mengumumkan, memberitahukan@_@false@_@true@-@"
			+ "annoy@_@mengganggu@_@false@_@true@-@"
			+ "annual@_@buku tahunan, tahunan@_@false@_@true@-@"
			+ "ante@_@taruhan@_@false@_@false@-@"
			+ "anxiety@_@kegelisahan@_@false@_@false@-@"
			+ "anxious@_@khawatir, cemas, gelisah@_@false@_@false@-@"
			+ "apart@_@berpisahan, selain, terlepas@_@false@_@true@-@"
			+ "apologize@_@minta maaf@_@false@_@true@-@"
			+ "apotheosis@_@perwujudan yg sempurna@_@true@_@false@-@"
			+ "appal@_@menggemparkan@_@true@_@false@-@"
			+ "appeal@_@seruan@_@false@_@false@-@"
			+ "appendictis@_@radang usus buntu@_@false@_@true@-@"
			+ "appetite@_@nafsu makan@_@false@_@true@-@"
			+ "apprehend@_@menahan, menawan@_@true@_@false@-@"
			+ "approximately@_@kira-kira@_@false@_@false@-@"
			+ "archaic@_@kuno, kolot, lama@_@false@_@false@-@"
			+ "arid@_@gersang, kering@_@false@_@false@-@"
			+ "arrangement@_@pengaturan, susunan@_@true@_@false@-@"
			+ "ascetic@_@pertapa@_@true@_@false@-@"
			+ "ashame@_@malu@_@true@_@false@-@"
			+ "ashore@_@ke darat(kapal)@_@false@_@false@-@"
			+ "ashtray@_@asbak@_@true@_@false@-@"
			+ "aside@_@disamping@_@false@_@true@-@"
			+ "askew@_@miring@_@true@_@false@-@"
			+ "asphyxia@_@keadaan sesak napas@_@false@_@true@-@"
			+ "assemble@_@berkumpul@_@true@_@false@-@"
			+ "assistance@_@bantuan@_@false@_@true@-@"
			+ "assure@_@jamin, percaya@_@false@_@true@-@"
			+ "astonish@_@mencengangkan, mengherankan@_@true@_@false@-@"
			+ "astound@_@mengherankan, mengejutkan@_@false@_@false@-@"
			+ "astray@_@kesasar, tersesat@_@false@_@true@-@"
			+ "atone@_@bertaubat@_@false@_@false@-@"
			+ "attain@_@mencapai@_@false@_@false@-@"
			+ "attempt@_@percobaan@_@false@_@true@-@"
			+ "attendant@_@pembantu, pelayan@_@false@_@true@-@"
			+ "auction@_@lelang@_@true@_@false@-@"
			+ "audacity@_@keberanian@_@true@_@false@-@"
			+ "auntie@_@bibi, tante@_@false@_@true@-@"
			+ "authority@_@kewenangan@_@false@_@true@-@"
			+ "avalanche@_@es/salju longsor@_@false@_@true@-@"
			+ "avenge@_@membalas dendam@_@false@_@true@-@"
			+ "awake@_@bangun@_@false@_@true@-@"
			+ "awful@_@mengerikan@_@false@_@true@-@"
			+ "awfully@_@sekali, sangat@_@false@_@true@-@"
			+ "awkward@_@aneh, janggal@_@false@_@true@-@"
			+ "bacon@_@daging babi yg diasin dan dikukus@_@false@_@false@-@"
			+ "badge@_@lencana@_@false@_@false@-@"
			+ "badger@_@semacam bakul/tukang@_@false@_@false@-@"
			+ "baffle@_@mengherankan@_@true@_@false@-@"
			+ "bag@_@kantong, tas@_@false@_@true@-@"
			+ "bait@_@umpan@_@false@_@false@-@"
			+ "bald@_@botak@_@false@_@false@-@"
			+ "banal@_@dangkal, biasa@_@false@_@true@-@"
			+ "bandage@_@perban, membalut@_@false@_@true@-@"
			+ "banish@_@membuang@_@false@_@false@-@"
			+ "bankrupt@_@orang bangkrut@_@false@_@true@-@"
			+ "banquet@_@perjamuan@_@false@_@true@-@"
			+ "bare@_@gundul@_@false@_@false@-@"
			+ "barely@_@baru saja@_@false@_@false@-@"
			+ "bargain@_@tawar-menawar@_@false@_@true@-@"
			+ "bark@_@gonggongan@_@false@_@true@-@"
			+ "barrel@_@tong@_@false@_@true@-@"
			+ "barrier@_@rintangan@_@false@_@false@-@"
			+ "beam@_@balok, sinar@_@false@_@true@-@"
			+ "bear@_@memikul, beruang@_@false@_@true@-@"
			+ "beaver@_@berang berang@_@false@_@true@-@"
			+ "beckon@_@memberi isyarat@_@false@_@false@-@"
			+ "befall@_@menimpa@_@true@_@false@-@"
			+ "beg@_@meminta, mengemis@_@false@_@true@-@"
			+ "behalf@_@kepentingan@_@true@_@false@-@"
			+ "beneath@_@dibawah@_@false@_@false@-@"
			+ "beneficiary@_@ahli waris@_@true@_@false@-@"
			+ "berserk@_@mengamuk@_@false@_@true@-@"
			+ "besmirch@_@menodai@_@true@_@false@-@"
			+ "bestow@_@memberikan, melimpahkan@_@false@_@true@-@"
			+ "betray@_@menghianati@_@false@_@true@-@"
			+ "beyond@_@melebihi, melewati@_@false@_@true@-@"
			+ "bicker@_@bercekcok@_@false@_@true@-@"
			+ "bizarre@_@ajaib, aneh, ganjil@_@false@_@true@-@"
			+ "blabber@_@suka berbicara dg tak memikirkan akibatnya@_@false@_@true@-@"
			+ "blasphemous@_@yg menghina tuhan@_@true@_@false@-@"
			+ "blasphemy@_@penghujatan, pemfitnahan@_@true@_@false@-@"
			+ "blasted@_@meledakan@_@false@_@true@-@"
			+ "blatant@_@menyolok mata,, ribut dg terang-terangan@_@true@_@false@-@"
			+ "bloom@_@kumpulan bunga@_@false@_@true@-@"
			+ "blow@_@pukulan, tamparan, meniup, bertiup@_@false@_@true@-@"
			+ "bludgeon@_@gada, pemukul@_@false@_@false@-@"
			+ "bluff@_@gertak sambal@_@false@_@true@-@"
			+ "blunt@_@menjadikan tumpul@_@true@_@false@-@"
			+ "blurt@_@mengatakan sesuatu yg harus , dirahasaikan@_@false@_@false@-@"
			+ "blush@_@merah muka@_@false@_@true@-@"
			+ "booze@_@minuman keras@_@false@_@false@-@"
			+ "botch@_@merusak pekerjaan@_@false@_@false@-@"
			+ "bother@_@kesusahan, menyusahkan@_@false@_@true@-@"
			+ "bout@_@pertandingan@_@false@_@true@-@"
			+ "bow@_@tundukan, membungkuk, , menundukan kepala@_@true@_@false@-@"
			+ "bowel@_@isi perut@_@true@_@false@-@"
			+ "brag@_@membual@_@false@_@false@-@"
			+ "brat@_@anak nakal@_@false@_@true@-@"
			+ "brawl@_@ribut, percekcokan@_@true@_@false@-@"
			+ "brazen@_@kurang ajar, tak tahu malu@_@true@_@false@-@"
			+ "breed@_@menternakkan@_@false@_@true@-@"
			+ "brew@_@membuat, timbul, terjadi@_@false@_@false@-@"
			+ "bride@_@pengantin perempuan@_@false@_@false@-@"
			+ "briefly@_@dg singkat@_@true@_@false@-@"
			+ "brim@_@meluap@_@false@_@false@-@"
			+ "bruise@_@memar@_@false@_@true@-@"
			+ "brutish@_@kasar, kebinatangan@_@true@_@false@-@"
			+ "budge@_@berpindah tempat@_@false@_@false@-@"
			+ "buffoon@_@pelawak, badut@_@false@_@true@-@"
			+ "bulky@_@besar sekali@_@true@_@false@-@"
			+ "bump@_@benjol, jendul@_@false@_@false@-@"
			+ "buoy@_@pelampung@_@true@_@false@-@"
			+ "buoyant@_@bisa mengapung@_@false@_@false@-@"
			+ "burden@_@beban, pokok@_@false@_@true@-@"
			+ "burglar@_@pencuri@_@false@_@true@-@"
			+ "burial@_@pemakaman, penguburan@_@false@_@false@-@"
			+ "burly@_@besar dan tegap@_@true@_@false@-@"
			+ "bury@_@mengubur@_@true@_@false@-@"
			+ "bush@_@semak\"@_@false@_@true@-@"
			+ "butcher@_@tukang daging, jagal@_@false@_@false@-@"
			+ "butler@_@kepala pelayan@_@false@_@true@-@"
			+ "bystanders@_@penonton@_@false@_@true@-@"
			+ "caboose@_@gerbong tukang rem@_@false@_@false@-@"
			+ "cahoot@_@bekerjasama(dg rahasia)@_@true@_@false@-@"
			+ "cane@_@tongkat, roatn@_@true@_@false@-@"
			+ "capable@_@cakap, mampu, sanggup@_@false@_@true@-@"
			+ "cape@_@mantel tanpa lengan@_@false@_@true@-@"
			+ "capricious@_@tak terduga-duga@_@false@_@false@-@"
			+ "captivate@_@memikat hati@_@false@_@true@-@"
			+ "captive@_@tahanan, tawanan@_@false@_@true@-@"
			+ "carriage@_@kereta kuda, sikap diri@_@true@_@false@-@"
			+ "carry@_@membawa@_@false@_@true@-@"
			+ "carve@_@memahat@_@false@_@true@-@"
			+ "casket@_@peti mayat@_@true@_@false@-@"
			+ "catastrophe@_@malapetaka@_@true@_@false@-@"
			+ "cautious@_@berhati hati@_@false@_@false@-@"
			+ "cave@_@goa@_@false@_@true@-@"
			+ "cease@_@berhenti@_@true@_@false@-@"
			+ "ceiling@_@langit-langit@_@false@_@true@-@"
			+ "centipede@_@lipan@_@true@_@false@-@"
			+ "certain@_@pasti@_@false@_@true@-@"
			+ "chalet@_@villa kecil di pegunungan@_@false@_@false@-@"
			+ "chamber@_@kamar, bilik, ruangan@_@false@_@true@-@"
			+ "chaotic@_@kacau-balau@_@false@_@true@-@"
			+ "chaperon@_@bertindak sebagai penjaga@_@false@_@true@-@"
			+ "charcoal@_@arang@_@false@_@true@-@"
			+ "charity@_@kemurahan hati@_@true@_@false@-@"
			+ "charm@_@daya tarik, pesona@_@false@_@false@-@"
			+ "chastity@_@kesucian@_@false@_@false@-@"
			+ "chauffeur@_@pengemudi mobil@_@false@_@true@-@"
			+ "cheeky@_@bermuka tebal@_@false@_@false@-@"
			+ "chest@_@dada, peti, lemari@_@false@_@false@-@"
			+ "chew@_@kunyahan, mengunyah@_@false@_@true@-@"
			+ "chime@_@bunyi lonceng@_@true@_@false@-@"
			+ "chimney@_@cerobong asap@_@false@_@true@-@"
			+ "chirp@_@mengerik@_@false@_@false@-@"
			+ "chivalrous@_@sangat sopan@_@true@_@false@-@"
			+ "chop@_@potongan@_@false@_@false@-@"
			+ "chore@_@pekerjaan, tugas@_@true@_@false@-@"
			+ "chum@_@berteman, sahabat karib@_@true@_@false@-@"
			+ "chunk@_@bongkah, potong, gumpal@_@false@_@false@-@"
			+ "cipher@_@sandi rahasia@_@true@_@false@-@"
			+ "circumstance@_@keadaan@_@false@_@true@-@"
			+ "cite@_@menyebutkan, memuji@_@true@_@false@-@"
			+ "clamor@_@kegerangan, teriakan@_@false@_@true@-@"
			+ "clash@_@bentrokan@_@false@_@false@-@"
			+ "clerk@_@pegawai toko@_@true@_@false@-@"
			+ "cloak@_@jubah, mantel@_@false@_@true@-@"
			+ "clutch@_@cengkraman@_@true@_@false@-@"
			+ "coal@_@batu bara@_@true@_@false@-@"
			+ "coarse@_@kasar@_@false@_@true@-@"
			+ "coast@_@pantai, pesisir@_@true@_@false@-@"
			+ "coat@_@jas, mentel, melapisi@_@false@_@false@-@"
			+ "cocky@_@sombong, congak@_@true@_@false@-@"
			+ "coexist@_@hidup bersama, berdamingan@_@false@_@true@-@"
			+ "coffin@_@peti mati@_@false@_@true@-@"
			+ "coincide@_@bertepatan@_@false@_@false@-@"
			+ "coincidence@_@kejadian yg kebetulan@_@false@_@true@-@"
			+ "collide@_@bertubrukan@_@true@_@false@-@"
			+ "comatose@_@pingsan, tidak sadar diri@_@false@_@true@-@"
			+ "commit@_@melakukan, berbuat@_@false@_@true@-@"
			+ "commotion@_@keributan, huru hara@_@false@_@false@-@"
			+ "compassion@_@perasaan terharu@_@true@_@false@-@"
			+ "compassionate@_@sangat merasa kasihan@_@true@_@false@-@"
			+ "compliment@_@pujian, salam@_@false@_@true@-@"
			+ "compose@_@menyusun@_@false@_@false@-@"
			+ "comprehend@_@memahami, mengerti@_@true@_@false@-@"
			+ "compromise@_@membahayakan@_@true@_@false@-@"
			+ "compulsory@_@diwajibkan@_@true@_@false@-@"
			+ "comrade@_@kawan, sahabat, saudara@_@false@_@true@-@"
			+ "conceal@_@menyembunyikan@_@false@_@false@-@"
			+ "conceit@_@kesombongan@_@true@_@false@-@"
			+ "concert@_@konser@_@false@_@true@-@"
			+ "condemn@_@menghukum@_@true@_@false@-@"
			+ "condemnation@_@penghukuman@_@true@_@false@-@"
			+ "conduct@_@mengadakan, tingkah laku@_@true@_@false@-@"
			+ "confectionery@_@tempat penjualan gula\"@_@false@_@true@-@"
			+ "confess@_@mengakui, mengaku@_@false@_@true@-@"
			+ "confetti@_@guntingan kertas yg berwarna yg, dihamburkan pada waktu pesta@_@true@_@false@-@"
			+ "confine@_@menahan, mengurung@_@true@_@false@-@"
			+ "confiscate@_@menyita@_@false@_@false@-@"
			+ "congest@_@menumpuk@_@false@_@false@-@"
			+ "conscience@_@suara hati, kata hati@_@false@_@false@-@"
			+ "conscious@_@sadar@_@false@_@true@-@"
			+ "conserve@_@menghemat(energi)@_@true@_@false@-@"
			+ "consider@_@mempertimbangkan@_@false@_@true@-@"
			+ "considerable@_@sekali, amat@_@false@_@false@-@"
			+ "considerate@_@penuh perhatian, baik budi@_@false@_@false@-@"
			+ "constitution@_@undang undang dasar, keadaan jasamni@_@false@_@true@-@"
			+ "contemplate@_@merenungkan@_@false@_@false@-@"
			+ "content@_@puas, isi, daya muat@_@false@_@false@-@"
			+ "Contractions@_@singkatan@_@true@_@false@-@"
			+ "contraption@_@pesawat yang aneh@_@true@_@false@-@"
			+ "contrary@_@kebalikan@_@false@_@true@-@"
			+ "convenient@_@tidak menyusahkan, baik sekali@_@false@_@false@-@"
			+ "convey@_@menyampaikan@_@true@_@false@-@"
			+ "convict@_@narapidana@_@false@_@true@-@"
			+ "convince@_@meyakinkan@_@false@_@false@-@"
			+ "cope@_@mengatasi, menguasai@_@false@_@false@-@"
			+ "cord@_@kawat@_@false@_@true@-@"
			+ "corpse@_@mayat, jenazah@_@false@_@true@-@"
			+ "corroborate@_@menguatkan, membernarkan@_@true@_@false@-@"
			+ "corrode@_@berkarat@_@false@_@true@-@"
			+ "cottage@_@pondok, gubuk@_@false@_@false@-@"
			+ "course@_@jalan, kursus, pelajaran@_@false@_@false@-@"
			+ "courtesy@_@kesopan-santunan, rasa hormat@_@true@_@false@-@"
			+ "courtyard@_@halaman gedung@_@true@_@false@-@"
			+ "cove@_@teluk kecil@_@true@_@false@-@"
			+ "coward@_@pengecut, penakut@_@false@_@true@-@"
			+ "crammed@_@berdasarkan@_@false@_@false@-@"
			+ "crap@_@omong kosong@_@false@_@true@-@"
			+ "crate@_@peti kayu@_@false@_@false@-@"
			+ "creche@_@penitipan bayi@_@false@_@true@-@"
			+ "creepy@_@menyeramkan@_@false@_@true@-@"
			+ "crest@_@puncak, kepala@_@true@_@false@-@"
			+ "crook@_@penjahat, bajingan@_@false@_@false@-@"
			+ "crucial@_@penting sekali, kritis@_@false@_@true@-@"
			+ "crucify@_@menyalib@_@false@_@false@-@"
			+ "cruel@_@kejam, bengis@_@false@_@true@-@"
			+ "cruise@_@pelayaran, menjelajah@_@false@_@true@-@"
			+ "cruising@_@menjelajah@_@false@_@true@-@"
			+ "crumble@_@remuk, hancur@_@true@_@false@-@"
			+ "crust@_@kerak, lapisan kulit@_@false@_@true@-@"
			+ "cuisine@_@masakan, santapan@_@false@_@false@-@"
			+ "culprit@_@orang yg telah melakukan kejahatan@_@false@_@true@-@"
			+ "curiosity@_@keingintahuan@_@false@_@true@-@"
			+ "curious@_@ingin tahu, heran@_@false@_@true@-@"
			+ "curly@_@keriting@_@false@_@true@-@"
			+ "curry@_@masakan kari@_@false@_@true@-@"
			+ "curse@_@kutukan@_@false@_@true@-@"
			+ "curtain@_@gorden, tirai@_@true@_@false@-@"
			+ "curve@_@membelok, tikungan@_@false@_@true@-@"
			+ "custody@_@tahanan, penjagaan@_@false@_@true@-@"
			+ "dare@_@tantangan, bertindak berani@_@false@_@true@-@"
			+ "dawn@_@subuh, fajar@_@false@_@false@-@"
			+ "deaf@_@tuli@_@false@_@true@-@"
			+ "decade@_@dekade, dasawarsa@_@true@_@false@-@"
			+ "decay@_@kebusukan, kehilangan@_@false@_@false@-@"
			+ "decease@_@kematian@_@true@_@false@-@"
			+ "decedent@_@orang yg meninggal@_@true@_@false@-@"
			+ "deceive@_@menipu, mengelabui@_@false@_@false@-@"
			+ "decency@_@kelakuan baik, kesusilaan@_@true@_@false@-@"
			+ "deception@_@penipuan, muslihat@_@true@_@false@-@"
			+ "decipher@_@menguraikan@_@true@_@false@-@"
			+ "decisive@_@menentukan@_@false@_@false@-@"
			+ "declining@_@menurun, yg berkurang@_@true@_@false@-@"
			+ "decoy@_@umpan@_@false@_@false@-@"
			+ "decrepit@_@jompo, tua sekali@_@false@_@true@-@"
			+ "deduce@_@menyimpulkan, , menarik kesimpulan@_@false@_@true@-@"
			+ "deed@_@perbuatan@_@false@_@true@-@"
			+ "deem@_@menganggap@_@true@_@false@-@"
			+ "deface@_@merusak, mencacati@_@false@_@true@-@"
			+ "definite@_@tertentu, pasti@_@true@_@false@-@"
			+ "defy@_@menentang(order)@_@false@_@true@-@"
			+ "deliberate@_@tenang dan berhati\"@_@true@_@false@-@"
			+ "delight@_@senang@_@false@_@true@-@"
			+ "delineate@_@menggambarkan@_@false@_@true@-@"
			+ "delinquent@_@penjahat, nakal@_@true@_@false@-@"
			+ "delirious@_@mengigau, lupa daratan @_@true@_@false@-@"
			+ "demand@_@permintaan, menuntut@_@false@_@true@-@"
			+ "demeanor@_@sikap, cara bertindak@_@false@_@false@-@"
			+ "demise@_@kematian@_@false@_@true@-@"
			+ "denim@_@jeans@_@true@_@false@-@"
			+ "depart@_@berangkat@_@false@_@true@-@"
			+ "departure@_@keberangkatan@_@false@_@true@-@"
			+ "depict@_@menggambarkan@_@false@_@true@-@"
			+ "deplorable@_@tercela, menyedihkan@_@true@_@false@-@"
			+ "deprave@_@merusak akhlak@_@true@_@false@-@"
			+ "derision@_@ejekan, cemohan@_@true@_@false@-@"
			+ "desert@_@gurun, meninggalkan@_@false@_@true@-@"
			+ "deserter@_@pembelot@_@true@_@false@-@"
			+ "deserve@_@pantas menrima, berhak mendapat@_@false@_@false@-@"
			+ "deserved@_@menghargai@_@false@_@false@-@"
			+ "desire@_@hasrat@_@false@_@true@-@"
			+ "despair@_@keputusasaan@_@true@_@false@-@"
			+ "despicable@_@tercela@_@true@_@false@-@"
			+ "despise@_@memandang rendah terhadap@_@false@_@false@-@"
			+ "despite@_@meskipun, walaupun@_@false@_@true@-@"
			+ "destine@_@mentakdirkan, memperuntukan@_@true@_@false@-@"
			+ "destruction@_@pekerjaan menghancurkan@_@false@_@true@-@"
			+ "detach@_@melepaskan@_@true@_@false@-@"
			+ "detain@_@menawan, menahan@_@true@_@false@-@"
			+ "detest@_@benci@_@false@_@false@-@"
			+ "detour@_@jalan memutar@_@false@_@false@-@"
			+ "devastate@_@meluluhkan@_@true@_@false@-@"
			+ "devious@_@berliku liku@_@false@_@true@-@"
			+ "devise@_@memikirkan, merencanakan@_@true@_@false@-@"
			+ "devote@_@mencurahkan@_@true@_@false@-@"
			+ "devotion@_@kesetiaan@_@true@_@false@-@"
			+ "devour@_@menganyang@_@false@_@false@-@"
			+ "dew@_@embun@_@true@_@false@-@"
			+ "dice@_@memotong-motong@_@false@_@false@-@"
			+ "digest@_@dicerna@_@false@_@true@-@"
			+ "dignity@_@martabat@_@true@_@false@-@"
			+ "dilate@_@membesar@_@true@_@false@-@"
			+ "diligence@_@ketekunan@_@false@_@true@-@"
			+ "disarray@_@kekacauan@_@false@_@true@-@"
			+ "disaster@_@bencana@_@false@_@true@-@"
			+ "disciple@_@murid@_@false@_@true@-@"
			+ "discreet@_@bijaksana, berhati\"@_@false@_@true@-@"
			+ "disguise@_@penyamaran@_@false@_@true@-@"
			+ "dish@_@hidangan@_@false@_@true@-@"
			+ "dismantle@_@membongkar@_@true@_@false@-@"
			+ "dismay@_@kecemasan@_@false@_@false@-@"
			+ "dispel@_@menghilangkan@_@false@_@true@-@"
			+ "disperse@_@membubarkan@_@true@_@false@-@"
			+ "disposed@_@mengatur, menentukan@_@true@_@false@-@"
			+ "dispute@_@perselisihan@_@true@_@false@-@"
			+ "disrupted@_@mengacaukan, mengganggu@_@false@_@true@-@"
			+ "dissect@_@membedah@_@true@_@false@-@"
			+ "distract@_@mengalihkan@_@false@_@true@-@"
			+ "divert@_@mengalihkan@_@false@_@true@-@"
			+ "divine@_@bersifat ketuhanan@_@false@_@true@-@"
			+ "divorce@_@bercerai@_@false@_@true@-@"
			+ "dizzy@_@pusing@_@false@_@true@-@"
			+ "docile@_@jinak@_@false@_@true@-@"
			+ "doom@_@menemui ajal@_@false@_@false@-@"
			+ "dope@_@obat bius seperti morfin@_@false@_@true@-@"
			+ "doubt@_@ragu-ragu@_@false@_@true@-@"
			+ "douche@_@semprotan air@_@true@_@false@-@"
			+ "doused@_@disiram@_@false@_@true@-@"
			+ "dove@_@dive@_@false@_@true@-@"
			+ "drain@_@saluran@_@false@_@true@-@"
			+ "draw@_@tarikan, seri@_@true@_@false@-@"
			+ "drift@_@penyimpanan, arus@_@true@_@false@-@"
			+ "drought@_@masa kekeringan@_@false@_@false@-@"
			+ "dubious@_@yg meragukan@_@false@_@true@-@"
			+ "duct@_@pipa, saluran@_@true@_@false@-@"
			+ "due@_@seharusnya, hak@_@true@_@false@-@"
			+ "dull@_@tumpul, pudar@_@false@_@true@-@"
			+ "dumb@_@bodoh@_@false@_@true@-@"
			+ "dump@_@membuang, tempat sampah@_@false@_@true@-@"
			+ "dunce@_@anak yg dungu@_@true@_@false@-@"
			+ "duty@_@tugas, kewajiban@_@false@_@true@-@"
			+ "dwell@_@tempat tinggal, kediaman@_@true@_@false@-@"
			+ "eagerly@_@dgn tidak sabar@_@false@_@true@-@"
			+ "eavesdrop@_@mendengarkan rahasia orang, mendengarkan secara diam\"@_@false@_@true@-@"
			+ "echelon@_@tingkatan kekuasaan@_@true@_@false@-@"
			+ "edible@_@dapat dimakan@_@false@_@true@-@"
			+ "eel@_@belut@_@true@_@false@-@"
			+ "either@_@salah seorang@_@false@_@true@-@"
			+ "elaborate@_@terperinci, rumit, teliti@_@false@_@true@-@"
			+ "elder@_@lebih tua, senior@_@false@_@true@-@"
			+ "election@_@pemilihan@_@false@_@true@-@"
			+ "embankment@_@tanggul, tambak@_@true@_@false@-@"
			+ "embed@_@menanamkan, melekatkan@_@false@_@true@-@"
			+ "embodiment@_@perwujudan, penjelmaan@_@true@_@false@-@"
			+ "embrace@_@memeluk@_@false@_@true@-@"
			+ "eminent@_@ulung, unggul@_@true@_@false@-@"
			+ "emit@_@memancarkan@_@false@_@true@-@"
			+ "empress@_@kaisar wanita@_@false@_@false@-@"
			+ "encore@_@meminta menyanyi ulang@_@false@_@true@-@"
			+ "encourage@_@mendorong@_@true@_@false@-@"
			+ "endure@_@manahan@_@false@_@false@-@"
			+ "engage@_@mengikutsertakan@_@true@_@false@-@"
			+ "engraver@_@pemahat@_@false@_@true@-@"
			+ "engulf@_@meliputi, melanda@_@true@_@false@-@"
			+ "engulfs@_@meliputi, melanda@_@false@_@true@-@"
			+ "enhance@_@mempertinggi@_@false@_@false@-@"
			+ "enormous@_@besar sekali@_@false@_@true@-@"
			+ "enroll@_@mendaftarkan@_@false@_@true@-@"
			+ "ensure@_@menjamin, memastikan@_@false@_@true@-@"
			+ "enthusiastic@_@antusias, bersemangat@_@false@_@true@-@"
			+ "entrance@_@pintu masuk@_@false@_@true@-@"
			+ "entwine@_@menjalin@_@false@_@true@-@"
			+ "envoy@_@duta, utusan, wakil@_@true@_@false@-@"
			+ "envy@_@iri, cemburu@_@false@_@true@-@"
			+ "epidemic@_@wabah@_@false@_@true@-@"
			+ "equation@_@persamaan@_@false@_@true@-@"
			+ "errand@_@suruhan@_@true@_@false@-@"
			+ "escort@_@menemani@_@false@_@false@-@"
			+ "eternal@_@abadi@_@false@_@true@-@"
			+ "evaporate@_@menguap@_@false@_@true@-@"
			+ "eventually@_@secepatnya@_@false@_@true@-@"
			+ "evict@_@mengusir@_@true@_@false@-@"
			+ "evoke@_@membangkitkan@_@false@_@true@-@"
			+ "examination@_@pemeriksaan@_@false@_@false@-@"
			+ "excavation@_@panggilan@_@true@_@false@-@"
			+ "exceed@_@melebihi, melampaui@_@false@_@false@-@"
			+ "exceptional@_@luarbiasa, istimewa@_@false@_@false@-@"
			+ "excessive@_@berlebihan@_@true@_@false@-@"
			+ "exchange@_@pertukaran@_@false@_@true@-@"
			+ "excite@_@membangkitkan, menggairahkan@_@true@_@false@-@"
			+ "excitment@_@kegembiraan@_@false@_@true@-@"
			+ "excuse@_@pernyataan menyesal@_@false@_@false@-@"
			+ "exempt@_@dibebaskan@_@true@_@false@-@"
			+ "exert@_@menggunakan, mendesak@_@false@_@false@-@"
			+ "exhaust@_@meleleahkan, , menghabiskan tenaga@_@false@_@false@-@"
			+ "exhibit@_@pameran@_@false@_@false@-@"
			+ "exile@_@pengasingan@_@false@_@true@-@"
			+ "expect@_@mengharapkan@_@false@_@true@-@"
			+ "exquisite@_@indah sekali@_@false@_@true@-@"
			+ "extend@_@memperpanjang@_@false@_@false@-@"
			+ "extended@_@memperluas@_@false@_@false@-@"
			+ "extent@_@luas@_@false@_@false@-@"
			+ "extinct@_@binatang yg punah@_@false@_@true@-@"
			+ "extinguish@_@memadamkan@_@true@_@false@-@"
			+ "extort@_@memeras@_@true@_@false@-@"
			+ "extravagant@_@boros@_@false@_@true@-@"
			+ "faint@_@pingsan@_@false@_@false@-@"
			+ "fairly@_@(secara) wajar@_@true@_@false@-@"
			+ "fame@_@popularitas, kemasyhuran@_@false@_@true@-@"
			+ "fart@_@kentut@_@true@_@false@-@"
			+ "fascinate@_@mempesona@_@false@_@false@-@"
			+ "fasten@_@mengikatkan@_@false@_@false@-@"
			+ "fate@_@takdir, nasib@_@false@_@true@-@"
			+ "favor@_@kebaikan hati, kemurahan hati@_@false@_@true@-@"
			+ "faze@_@mengganggu@_@true@_@false@-@"
			+ "feast@_@mengadakan pesta@_@true@_@false@-@"
			+ "feat@_@prestasi@_@false@_@false@-@"
			+ "feather@_@bulu@_@false@_@false@-@"
			+ "feeble@_@lemah@_@false@_@true@-@"
			+ "feline@_@binatang termasuk keluarga kucing@_@false@_@true@-@"
			+ "fellas@_@kawan, bung@_@true@_@false@-@"
			+ "fellow@_@kawan, anggota@_@false@_@true@-@"
			+ "fencer@_@pemaing anggar@_@false@_@true@-@"
			+ "fencing@_@memagari@_@true@_@false@-@"
			+ "fend@_@menangkis, menolak@_@false@_@false@-@"
			+ "ferocious@_@ganas, buas, garang@_@true@_@false@-@"
			+ "ferocity@_@keganasan@_@true@_@false@-@"
			+ "fervent@_@kuat, keras, sungguh\"@_@true@_@false@-@"
			+ "fetch@_@mengambil, menjemput@_@false@_@true@-@"
			+ "fever@_@demam@_@false@_@true@-@"
			+ "fiance@_@tunangan@_@false@_@true@-@"
			+ "fiend@_@setan, iblis@_@false@_@true@-@"
			+ "fierce@_@sengit, dahsyat@_@false@_@false@-@"
			+ "filth@_@kotoran, sampah@_@true@_@false@-@"
			+ "filthy@_@kotor, dekil@_@true@_@false@-@"
			+ "fin@_@sirip@_@false@_@false@-@"
			+ "fishy@_@mencurigakan@_@false@_@true@-@"
			+ "flagrant@_@kesalhan yg menyolok@_@true@_@false@-@"
			+ "flair@_@pengamatan yg tajam@_@true@_@false@-@"
			+ "flat@_@datar, ban kempes@_@false@_@true@-@"
			+ "flatter@_@merayu, menyanjung@_@false@_@false@-@"
			+ "flaw@_@kekurangan@_@false@_@false@-@"
			+ "fleet@_@armada@_@false@_@false@-@"
			+ "flinch@_@menjauhkan diri@_@true@_@false@-@"
			+ "float@_@terapung@_@false@_@true@-@"
			+ "flourish@_@berjalan baik@_@true@_@false@-@"
			+ "fluent@_@lancar@_@true@_@false@-@"
			+ "fluid@_@cairan@_@false@_@true@-@"
			+ "fluke@_@kebetulan@_@false@_@false@-@"
			+ "fog@_@kabut@_@true@_@false@-@"
			+ "foil@_@menggagalkan@_@false@_@true@-@"
			+ "foldable@_@dilipat@_@false@_@true@-@"
			+ "folk@_@rakyat@_@false@_@true@-@"
			+ "foreclosure@_@penyitaan@_@false@_@false@-@"
			+ "forfeit@_@penebusan@_@true@_@false@-@"
			+ "fort@_@benteng@_@true@_@false@-@"
			+ "forte@_@keahlian@_@false@_@false@-@"
			+ "forth@_@seterusnya@_@true@_@false@-@"
			+ "fortunately@_@untung, untunglah, syukur@_@false@_@true@-@"
			+ "fracture@_@patah, retak@_@true@_@false@-@"
			+ "fragile@_@rapuh@_@false@_@false@-@"
			+ "frail@_@lemah@_@true@_@false@-@"
			+ "frame@_@tuduhan palsu, bingkai@_@false@_@false@-@"
			+ "frank@_@jujur, berterus terang@_@false@_@true@-@"
			+ "fraud@_@penipuan@_@false@_@false@-@"
			+ "friction@_@pergesekan, pergeseran@_@false@_@true@-@"
			+ "fridge@_@peti es@_@false@_@false@-@"
			+ "fright@_@ketakutan@_@false@_@false@-@"
			+ "frill@_@jumbai\", hiasan tambahan@_@true@_@false@-@"
			+ "frolic@_@bersenang-senang@_@true@_@false@-@"
			+ "fugitive@_@buronan@_@false@_@false@-@"
			+ "funeral@_@pemakaman@_@false@_@true@-@"
			+ "furious@_@marah, geram@_@false@_@false@-@"
			+ "furnace@_@tungku pembakaran@_@true@_@false@-@"
			+ "furry@_@berbulu lembut@_@false@_@false@-@"
			+ "furthermore@_@selanjutnya@_@false@_@true@-@"
			+ "fuse@_@sekering@_@false@_@true@-@"
			+ "futile@_@sia sia@_@false@_@false@-@"
			+ "gain@_@keuntungan@_@false@_@true@-@"
			+ "gaol@_@penjara@_@true@_@false@-@"
			+ "gargantuan@_@raksasa, besarsekali@_@true@_@false@-@"
			+ "garlic@_@bawang putih@_@true@_@false@-@"
			+ "gene@_@plasma pembawa darah@_@false@_@true@-@"
			+ "genie@_@jin@_@false@_@true@-@"
			+ "giraffe@_@jerapah@_@false@_@true@-@"
			+ "glad@_@senang@_@false@_@true@-@"
			+ "glance@_@pandangan sekilas@_@false@_@true@-@"
			+ "glare@_@berkilau@_@false@_@true@-@"
			+ "glide@_@meluncur, terbang layang@_@true@_@false@-@"
			+ "glimpse@_@pandangan sekilas@_@false@_@true@-@"
			+ "gloomy@_@suram, murang@_@false@_@true@-@"
			+ "glorious@_@mulia, agung@_@false@_@false@-@"
			+ "glutton@_@seorang rakus, pelahap@_@false@_@true@-@"
			+ "gobble@_@berkokok@_@false@_@false@-@"
			+ "gorgeous@_@indah, permai@_@true@_@false@-@"
			+ "grace@_@gaya lemah gemulai@_@true@_@false@-@"
			+ "grant@_@dana bantuan, mengabulkan@_@true@_@false@-@"
			+ "grasp@_@genggaman@_@false@_@true@-@"
			+ "graze@_@mengembala@_@false@_@true@-@"
			+ "greedy@_@tamak, rakus@_@false@_@false@-@"
			+ "greet@_@menyambut@_@false@_@true@-@"
			+ "grief@_@kesedihan@_@false@_@true@-@"
			+ "grieve@_@bersedih hati@_@true@_@false@-@"
			+ "grill@_@alat pemanggang@_@true@_@false@-@"
			+ "grin@_@meringis@_@true@_@false@-@"
			+ "groom@_@pengantin laki\"@_@false@_@true@-@"
			+ "groove@_@alur, lekuk@_@false@_@false@-@"
			+ "grudge@_@dendam@_@false@_@true@-@"
			+ "guidance@_@bimbingan@_@true@_@false@-@"
			+ "guilty@_@bersalah, berdosa@_@true@_@false@-@"
			+ "gull@_@burung camar@_@false@_@true@-@"
			+ "gullet@_@kerongkongan@_@false@_@false@-@"
			+ "gulp@_@teguk@_@false@_@true@-@"
			+ "gut@_@keberanian, ketekunan@_@false@_@true@-@"
			+ "gutter@_@got, selokan@_@false@_@false@-@"
			+ "habit@_@kebiasaan@_@false@_@true@-@"
			+ "hag@_@perempuan sihir tua yg buruk@_@false@_@true@-@"
			+ "halt@_@berhenti, memberhentikan@_@false@_@true@-@"
			+ "haphazard@_@sembarangan, sembrono@_@true@_@false@-@"
			+ "hare@_@trewelu, kelinci@_@false@_@true@-@"
			+ "harm@_@kejahatan, kerugian@_@true@_@false@-@"
			+ "harsh@_@kasar@_@false@_@true@-@"
			+ "hassle@_@perkelahian@_@false@_@false@-@"
			+ "haul@_@mengangkut, menyeret, hasil tangkapan@_@false@_@true@-@"
			+ "havoc@_@malapetaka, menipu@_@false@_@true@-@"
			+ "hazy@_@berkabut@_@false@_@false@-@"
			+ "headquarter@_@markas besar@_@false@_@true@-@"
			+ "hearty@_@sungguh-sungguh@_@true@_@false@-@"
			+ "hefty@_@besar dan kuat@_@true@_@false@-@"
			+ "heir@_@pewaris, mewaris@_@false@_@false@-@"
			+ "hemorrhage@_@pendarahan@_@false@_@true@-@"
			+ "hence@_@karenanya, karena itu@_@false@_@false@-@"
			+ "hereby@_@dengan ini@_@false@_@false@-@"
			+ "heredity@_@keturunan@_@true@_@false@-@"
			+ "hesitate@_@ragu\"@_@false@_@true@-@"
			+ "hesitation@_@keragu-raguan@_@false@_@true@-@"
			+ "hew@_@menebang@_@false@_@false@-@"
			+ "hilarious@_@riang, gembira@_@false@_@false@-@"
			+ "hinder@_@menghalangi, merintangi@_@true@_@false@-@"
			+ "hindrance@_@halangan, rintangan@_@false@_@true@-@"
			+ "hitch@_@halangan, rintangan, memasang, merenggut@_@false@_@true@-@"
			+ "hog@_@babi@_@true@_@false@-@"
			+ "homicide@_@pembunuhan@_@false@_@true@-@"
			+ "hone@_@mengasah@_@true@_@false@-@"
			+ "honest@_@jujur, dengan terus terang@_@false@_@true@-@"
			+ "hoodlum@_@penjahat, buaya darat@_@false@_@true@-@"
			+ "horde@_@gerombolan, sekelompok@_@true@_@false@-@"
			+ "horrible@_@mengerikan@_@false@_@true@-@"
			+ "horrid@_@mengerikan@_@false@_@true@-@"
			+ "hostile@_@bermusuhan@_@true@_@false@-@"
			+ "hound@_@anjing@_@false@_@true@-@"
			+ "howl@_@teriak@_@false@_@true@-@"
			+ "huddle@_@berkumpul@_@true@_@false@-@"
			+ "humble@_@sederhana@_@false@_@false@-@"
			+ "humid@_@lembah@_@true@_@false@-@"
			+ "humiliate@_@menghina, memalukan@_@true@_@false@-@"
			+ "humiliation@_@penghinaan@_@false@_@true@-@"
			+ "hunk@_@bongkahan@_@false@_@true@-@"
			+ "hurl@_@melemparkan@_@true@_@false@-@"
			+ "hustle@_@buru buru@_@false@_@false@-@"
			+ "idle@_@bermalas-malasan@_@false@_@true@-@"
			+ "ignite@_@menyalakan(api), membakar@_@false@_@true@-@"
			+ "imbecile@_@dungu@_@false@_@false@-@"
			+ "immature@_@belum dewasa@_@false@_@true@-@"
			+ "immense@_@besar sekali@_@false@_@false@-@"
			+ "immobilize@_@melumpuhkan@_@false@_@true@-@"
			+ "immolate@_@mengorbankan@_@false@_@false@-@"
			+ "impale@_@menusuk@_@false@_@false@-@"
			+ "impatient@_@tidak sabar@_@false@_@true@-@"
			+ "impenetrable@_@tidak dapat dimasuki@_@true@_@false@-@"
			+ "impostor@_@penipu@_@false@_@true@-@"
			+ "impregnable@_@tdk terkalahkan@_@true@_@false@-@"
			+ "imprint@_@mencap@_@false@_@true@-@"
			+ "impudence@_@kelancangan@_@true@_@false@-@"
			+ "inanimate@_@benda tak bernyawa@_@true@_@false@-@"
			+ "incinerate@_@membakar@_@true@_@false@-@"
			+ "incision@_@irisan@_@false@_@true@-@"
			+ "inclination@_@kecenderungan@_@false@_@true@-@"
			+ "incognito@_@secara menyamar@_@false@_@true@-@"
			+ "incompetent@_@tidak cakap, tidak mampu@_@false@_@true@-@"
			+ "inconvenient@_@merepotkan@_@false@_@true@-@"
			+ "indeed@_@memang, sungguh-sungguh@_@false@_@false@-@"
			+ "indication@_@indikasi, petunjuk@_@false@_@true@-@"
			+ "indispensable@_@sangat diperlukan@_@true@_@false@-@"
			+ "indisputable@_@tak dpt disangkal lagi@_@false@_@false@-@"
			+ "indulge@_@memuaskan diri@_@true@_@false@-@"
			+ "inevitable@_@tak dapat di elakan, pasti terjadi@_@false@_@false@-@"
			+ "infallible@_@sempurna, mutlak@_@true@_@false@-@"
			+ "inferior@_@orang bawahan@_@true@_@false@-@"
			+ "infiltrate@_@merembas@_@false@_@true@-@"
			+ "infirmary@_@rumah sakit / pengobatan@_@true@_@false@-@"
			+ "influence@_@pengaruh@_@false@_@true@-@"
			+ "infuriate@_@memarahkan@_@false@_@true@-@"
			+ "ingenious@_@banyak akal@_@false@_@true@-@"
			+ "ingest@_@menelan@_@true@_@false@-@"
			+ "ingrate@_@orang yg tak berterima kasih@_@true@_@false@-@"
			+ "inheritance@_@warisan@_@false@_@true@-@"
			+ "innate@_@pembawaan lahir@_@false@_@false@-@"
			+ "innocent@_@tidak bersalah@_@false@_@true@-@"
			+ "inquire@_@menanyakan, meminta keterangan@_@true@_@false@-@"
			+ "insane@_@gila, sakit pikiran@_@false@_@true@-@"
			+ "insist@_@memaksa@_@false@_@false@-@"
			+ "insolence@_@sikap sombong, penghinaan@_@true@_@false@-@"
			+ "insolent@_@besar mulut, kurang ajar@_@true@_@false@-@"
			+ "inspect@_@memeriksa@_@false@_@true@-@"
			+ "instead@_@malahan, daripada@_@false@_@false@-@"
			+ "instigator@_@penghasut@_@true@_@false@-@"
			+ "insult@_@penghinaan@_@false@_@true@-@"
			+ "insurrection@_@pemberontakan, huru-hara@_@false@_@false@-@"
			+ "intact@_@utuh, lengkap@_@true@_@false@-@"
			+ "intend@_@bermaksud untuk@_@false@_@true@-@"
			+ "intent@_@maksud@_@false@_@true@-@"
			+ "intention@_@niat@_@true@_@false@-@"
			+ "intentional@_@disengaja@_@false@_@false@-@"
			+ "interfere@_@mencampuri@_@false@_@true@-@"
			+ "intersection@_@persimpangan@_@false@_@true@-@"
			+ "intrigue@_@tipu daya, intrik@_@false@_@true@-@"
			+ "invade@_@menyerbu@_@false@_@false@-@"
			+ "invincible@_@tak terkalahkan@_@true@_@false@-@"
			+ "involve@_@melibatkan@_@true@_@false@-@"
			+ "irrefutable@_@tak terbantahkan@_@true@_@false@-@"
			+ "isle@_@pulau kecil@_@true@_@false@-@"
			+ "itch@_@kegatalan@_@false@_@true@-@"
			+ "ivy@_@semajam tumbuhan menjalar@_@false@_@true@-@"
			+ "jabber@_@ocehan, obrolan@_@true@_@false@-@"
			+ "jailbreak@_@pembongkaran, penjebolan@_@false@_@false@-@"
			+ "jinx@_@membawa sial@_@true@_@false@-@"
			+ "juncture@_@titik waktu@_@true@_@false@-@"
			+ "juvenile@_@anak muda@_@false@_@false@-@"
			+ "labor@_@tenaga kerja@_@false@_@true@-@"
			+ "lad@_@anak laki\", kacung@_@false@_@true@-@"
			+ "lamprey@_@ikan belut besar@_@true@_@false@-@"
			+ "lance@_@tombak@_@false@_@true@-@"
			+ "latch@_@mengancing@_@true@_@false@-@"
			+ "latent@_@terpendam, tersembunyi@_@false@_@false@-@"
			+ "lavish@_@mewah, berlebih\"an@_@true@_@false@-@"
			+ "lawn@_@halaman rumput@_@false@_@false@-@"
			+ "lax@_@longgar@_@false@_@true@-@"
			+ "leak@_@bocor@_@true@_@false@-@"
			+ "leap@_@lompatan@_@false@_@true@-@"
			+ "leather@_@kulit@_@true@_@false@-@"
			+ "leftover@_@sisa makan siang@_@false@_@true@-@"
			+ "legacy@_@harta pusaka, warisan@_@false@_@false@-@"
			+ "leisurely@_@tidak tergesa-gesa@_@false@_@true@-@"
			+ "lethal@_@yang mematikan@_@false@_@true@-@"
			+ "letting@_@membiarkan@_@false@_@true@-@"
			+ "lift@_@tumpangan, boncengan@_@false@_@true@-@"
			+ "lightly@_@dengan enteng@_@true@_@false@-@"
			+ "liking@_@kegemaran@_@false@_@true@-@"
			+ "linger@_@tetap hidup(walaupun sdh akn mati)@_@false@_@true@-@"
			+ "literally@_@secara harfiah@_@true@_@false@-@"
			+ "loathe@_@benci akan@_@false@_@true@-@"
			+ "lodging@_@penginapan@_@false@_@true@-@"
			+ "loiter@_@bergelandangan, berkeliaran@_@true@_@false@-@"
			+ "longing@_@keinginan@_@true@_@false@-@"
			+ "loose@_@lepas, bebas@_@false@_@true@-@"
			+ "lump@_@gumpalan@_@false@_@true@-@"
			+ "lunge@_@sergapan, serbuan mendadak@_@true@_@false@-@"
			+ "lure@_@daya tarik@_@false@_@true@-@"
			+ "lurk@_@bersembunyi@_@true@_@false@-@"
			+ "luster@_@kilauan@_@true@_@false@-@"
			+ "magnify@_@mebesar-besarkan@_@false@_@false@-@"
			+ "magpie@_@orang yg suka cerewet@_@false@_@false@-@"
			+ "malice@_@kedengkian, kebencian@_@false@_@true@-@"
			+ "mankind@_@umat manusia@_@true@_@false@-@"
			+ "manner@_@cara berbicara@_@false@_@false@-@"
			+ "mansion@_@rumah yg besar@_@false@_@true@-@"
			+ "mantis@_@belalang besar@_@false@_@true@-@"
			+ "marvelous@_@bagus sekali@_@false@_@true@-@"
			+ "massive@_@secara besar\"an@_@true@_@false@-@"
			+ "mast@_@tiang kapal@_@true@_@false@-@"
			+ "meager@_@kurus@_@true@_@false@-@"
			+ "meanie@_@orang kikir@_@false@_@true@-@"
			+ "meddle@_@mencampuri@_@true@_@false@-@"
			+ "meek@_@lembut, penurut@_@false@_@false@-@"
			+ "melt@_@melebur@_@false@_@true@-@"
			+ "menace@_@ancaman@_@true@_@false@-@"
			+ "menial@_@kasar(work), rendah@_@true@_@false@-@"
			+ "mention@_@menyebut@_@false@_@true@-@"
			+ "mere@_@belaka@_@false@_@false@-@"
			+ "merely@_@melulu@_@false@_@true@-@"
			+ "merrier@_@lebih riang gembira@_@false@_@false@-@"
			+ "midget@_@orang kerdil@_@false@_@false@-@"
			+ "might@_@kekuatan, tenaga, mungkin@_@true@_@false@-@"
			+ "mingle@_@bergaul, bercampur@_@true@_@false@-@"
			+ "minister@_@menteri@_@false@_@false@-@"
			+ "mirage@_@khayalan belaka@_@false@_@true@-@"
			+ "mischief@_@kenakalan@_@false@_@false@-@"
			+ "misery@_@kesengsaraan@_@false@_@false@-@"
			+ "mist@_@berkabut@_@false@_@true@-@"
			+ "moan@_@suara menggerang@_@false@_@true@-@"
			+ "moat@_@parit@_@true@_@false@-@"
			+ "mock@_@mengolok\"@_@false@_@true@-@"
			+ "mole@_@tahi lalat@_@false@_@true@-@"
			+ "moron@_@orang tolol@_@false@_@true@-@"
			+ "mosquito@_@nyamuk@_@false@_@true@-@"
			+ "moth@_@ngengat@_@true@_@false@-@"
			+ "motion@_@gerakan@_@false@_@true@-@"
			+ "mouldy@_@bulukan, lapuk@_@false@_@true@-@"
			+ "mourn@_@berkabung, berduka cita@_@false@_@true@-@"
			+ "mushy@_@cengeng@_@true@_@false@-@"
			+ "muttered@_@bergumam@_@false@_@true@-@"
			+ "nail@_@kuku, paku@_@true@_@false@-@"
			+ "naive@_@naif@_@false@_@true@-@"
			+ "nasty@_@tidak menyenangkan@_@false@_@true@-@"
			+ "necessary@_@penting, keperluan, kebutuhan@_@false@_@true@-@"
			+ "negligent@_@lalai@_@false@_@false@-@"
			+ "nerve@_@keberanian, kelanjangan, (urat) syaraf@_@false@_@true@-@"
			+ "nest@_@sarang@_@false@_@true@-@"
			+ "nimble@_@cekatan, cepat, gesit@_@true@_@false@-@"
			+ "nosedive@_@menukik, menjungkir@_@false@_@false@-@"
			+ "notorious@_@terkenal krn nm buruk@_@false@_@true@-@"
			+ "nuisance@_@gangguan@_@false@_@true@-@"
			+ "nullified@_@menghapuskan@_@false@_@true@-@"
			+ "numb@_@mati rasa@_@false@_@true@-@"
			+ "oar@_@dayung, kayuh@_@true@_@false@-@"
			+ "oath@_@sumpah@_@false@_@false@-@"
			+ "obedient@_@patuh, taat, penurut@_@false@_@false@-@"
			+ "obey@_@mematuhi, mentaati@_@false@_@true@-@"
			+ "obituary@_@berita kematian@_@true@_@false@-@"
			+ "obligation@_@kewajiban@_@false@_@false@-@"
			+ "obliterate@_@melenyapkan@_@true@_@false@-@"
			+ "obscene@_@cabul@_@true@_@false@-@"
			+ "obstacle@_@penghambat, rintangan, halangan@_@false@_@false@-@"
			+ "obstruct@_@menghalangi@_@true@_@false@-@"
			+ "obvious@_@nyata, jelas@_@false@_@true@-@"
			+ "occasion@_@saat, peristiwa, kejadian@_@false@_@false@-@"
			+ "occur@_@terjadi@_@false@_@true@-@"
			+ "odd@_@aneh, ganjil@_@false@_@true@-@"
			+ "ominous@_@tak menyenangkan@_@true@_@false@-@"
			+ "oppose@_@menentang@_@false@_@true@-@"
			+ "opposite@_@berlawanan@_@false@_@true@-@"
			+ "orb@_@bola, bulatan@_@false@_@true@-@"
			+ "ordinary@_@biasa@_@false@_@true@-@"
			+ "orphan@_@anak yatim@_@false@_@true@-@"
			+ "orphanage@_@rumah yatim piatu@_@false@_@true@-@"
			+ "ostrich@_@burung unta@_@false@_@true@-@"
			+ "ought@_@sebaiknya, seharusnya@_@true@_@false@-@"
			+ "outfit@_@pakaian@_@false@_@true@-@"
			+ "outrageous@_@menghina, menyakitkan hati@_@true@_@false@-@"
			+ "overwhelm@_@gembira@_@false@_@false@-@"
			+ "pact@_@perjanjian@_@true@_@false@-@"
			+ "paddle@_@dayung, kayuh@_@false@_@false@-@"
			+ "pal@_@sahabat, kawan@_@false@_@false@-@"
			+ "pale@_@pucat@_@false@_@true@-@"
			+ "palm@_@telapak tangan@_@true@_@false@-@"
			+ "palpitation@_@debaran jantung@_@false@_@true@-@"
			+ "pamper@_@memanjakan@_@false@_@true@-@"
			+ "pansy@_@banci@_@false@_@false@-@"
			+ "pardon@_@pengempunan@_@false@_@true@-@"
			+ "parted@_@memisahkan@_@false@_@true@-@"
			+ "particular @_@teliti, terutama sekali@_@true@_@false@-@"
			+ "passage@_@jalan lintasan@_@false@_@false@-@"
			+ "passion@_@keinginan besar@_@false@_@true@-@"
			+ "pathetic@_@menyedihkan@_@false@_@true@-@"
			+ "patience@_@kesabaran@_@false@_@true@-@"
			+ "patronage@_@perlindungan@_@false@_@false@-@"
			+ "pave@_@mengaspal(road)@_@true@_@false@-@"
			+ "paw@_@cakar@_@true@_@false@-@"
			+ "pawn@_@pion, bidak@_@false@_@true@-@"
			+ "peasant@_@petani@_@true@_@false@-@"
			+ "pedestrian@_@pejalan kaki@_@false@_@true@-@"
			+ "peek@_@mengintip@_@false@_@true@-@"
			+ "peerless@_@tak ada bandingannya@_@false@_@false@-@"
			+ "pendant@_@liontin@_@false@_@true@-@"
			+ "pendulum@_@bandul@_@true@_@false@-@"
			+ "peninsula@_@semenanjung@_@true@_@false@-@"
			+ "perhaps@_@barangkali@_@false@_@false@-@"
			+ "perish@_@binasa, mati, tewas@_@true@_@false@-@"
			+ "persistent@_@gigih@_@false@_@true@-@"
			+ "persuade@_@membujuk, mengajak, mendesak@_@false@_@false@-@"
			+ "pervert@_@seseorang yg sesat@_@false@_@true@-@"
			+ "pest@_@hama@_@false@_@true@-@"
			+ "pester@_@mengganggu@_@false@_@false@-@"
			+ "phrase@_@mengutarakan, ungkapan, ucapan, @_@false@_@true@-@"
			+ "pickle@_@acar, asinan@_@true@_@false@-@"
			+ "pierce@_@menembus@_@false@_@false@-@"
			+ "pile@_@tumpukan, gundukan@_@false@_@false@-@"
			+ "pilfered@_@meyerobot@_@false@_@true@-@"
			+ "pillow@_@bantal@_@false@_@true@-@"
			+ "pinch@_@jepitan, cubitan@_@false@_@false@-@"
			+ "pissed@_@sangat mabuk@_@false@_@true@-@"
			+ "pitiful@_@menyedihkan, tidak memuaskan@_@false@_@false@-@"
			+ "pivot@_@sumbu@_@false@_@true@-@"
			+ "plead@_@pembelaan@_@true@_@false@-@"
			+ "pleased@_@senang@_@false@_@true@-@"
			+ "pledge@_@janji, ikrar@_@true@_@false@-@"
			+ "plenty@_@banyak@_@false@_@true@-@"
			+ "plight@_@keadaan (buruk, sedih, jelek)@_@true@_@false@-@"
			+ "plough@_@membajak@_@false@_@false@-@"
			+ "plunder@_@barang\" rampasan@_@false@_@false@-@"
			+ "polish@_@semir, poles@_@false@_@true@-@"
			+ "polite@_@sopan santun@_@false@_@true@-@"
			+ "pomp@_@kemegahan, kebesaran@_@true@_@false@-@"
			+ "pond@_@kolam@_@false@_@true@-@"
			+ "pork@_@daging babi@_@false@_@false@-@"
			+ "portray@_@menggambarkan@_@false@_@true@-@"
			+ "possess@_@memiliki, mempunyai@_@false@_@false@-@"
			+ "postulate@_@mengemukakan sbg kenyataan@_@true@_@false@-@"
			+ "potter@_@pembuat barang-barang tembikar@_@false@_@false@-@"
			+ "pour@_@menuangkan(air)@_@false@_@false@-@"
			+ "poverty@_@kemiskinan@_@false@_@false@-@"
			+ "praise@_@salam@_@true@_@false@-@"
			+ "prank@_@kelakar, olok-olok@_@false@_@true@-@"
			+ "preach@_@khotbah, mengajarkan, menasehati@_@true@_@false@-@"
			+ "precaution@_@tindakan pencegahan@_@false@_@false@-@"
			+ "predict@_@meramalkan@_@false@_@true@-@"
			+ "prefer@_@lebih suka@_@false@_@false@-@"
			+ "preposterous@_@gila-gilaan, tidak masuk akal@_@true@_@false@-@"
			+ "presence@_@kehadiran@_@false@_@true@-@"
			+ "preservation@_@pengawetan@_@true@_@false@-@"
			+ "pretend@_@mengangap diri@_@false@_@false@-@"
			+ "pretense@_@berpura-pura, berdalih@_@true@_@false@-@"
			+ "prevent@_@mencegah@_@false@_@false@-@"
			+ "prey@_@mangsa@_@false@_@true@-@"
			+ "prior@_@lebih dahulu, sebelum@_@false@_@true@-@"
			+ "pristine@_@murni, asli@_@true@_@false@-@"
			+ "probably@_@mungkin@_@false@_@true@-@"
			+ "procure@_@memperoleh, mendapatkan@_@false@_@false@-@"
			+ "prodigy@_@keajaiban@_@true@_@false@-@"
			+ "profane@_@tidak sopan(language)@_@true@_@false@-@"
			+ "prognosticate@_@meramalkan@_@true@_@false@-@"
			+ "pronuciation@_@pengucapan@_@false@_@true@-@"
			+ "proof@_@bukti@_@false@_@true@-@"
			+ "proper@_@pantas@_@false@_@false@-@"
			+ "properly@_@dengan baik@_@false@_@true@-@"
			+ "prophecy@_@ramalan@_@true@_@false@-@"
			+ "propose@_@mengusulkan, menganjurkan, melamar@_@false@_@true@-@"
			+ "prosper@_@menjadi baik@_@false@_@false@-@"
			+ "prosperity@_@kemakmuran@_@true@_@false@-@"
			+ "prostrate@_@letih lesu, tak berdaya@_@true@_@false@-@"
			+ "pruning@_@memangkas@_@false@_@true@-@"
			+ "puddle@_@genangan air@_@false@_@false@-@"
			+ "puke@_@muntah@_@true@_@false@-@"
			+ "pulp@_@bubur, membuang ampas@_@false@_@false@-@"
			+ "pulverize@_@memipis, membubuk@_@false@_@false@-@"
			+ "punctual@_@tepat pada waktunya@_@false@_@false@-@"
			+ "puncture@_@tusukan@_@true@_@false@-@"
			+ "puppet@_@boneka@_@false@_@true@-@"
			+ "purify@_@membersihkan, menyucikan@_@true@_@false@-@"
			+ "purity@_@kemurnian@_@false@_@false@-@"
			+ "purr@_@dengkur@_@false@_@true@-@"
			+ "quarrel@_@perselisihan, percekcokan@_@true@_@false@-@"
			+ "racket@_@keributan, kegaduhan@_@false@_@false@-@"
			+ "raft@_@rakit@_@false@_@true@-@"
			+ "rage@_@kemarahan, kegusaran@_@false@_@true@-@"
			+ "rail@_@kereta api@_@false@_@false@-@"
			+ "ram@_@membenturkan@_@false@_@true@-@"
			+ "rampant@_@merajalela@_@true@_@false@-@"
			+ "ransack@_@menggedor@_@true@_@false@-@"
			+ "ransom@_@tebusan@_@false@_@true@-@"
			+ "rant@_@cakap besar@_@true@_@false@-@"
			+ "rare@_@jarang@_@false@_@true@-@"
			+ "rascal@_@bangsat, bajingan@_@true@_@false@-@"
			+ "rather@_@daripada@_@false@_@true@-@"
			+ "rattle@_@berketak-ketuk@_@false@_@true@-@"
			+ "ravage@_@membinasakan@_@true@_@false@-@"
			+ "ravine@_@jurang@_@true@_@false@-@"
			+ "realm@_@dunia, alam, kerajaan@_@true@_@false@-@"
			+ "rear@_@garis belakang@_@true@_@false@-@"
			+ "reassure@_@menentramkan hati@_@false@_@true@-@"
			+ "rebel@_@pemberontak, memberontak, yg suka menentang@_@false@_@true@-@"
			+ "receipt@_@tanda terima, kwitansi@_@false@_@true@-@"
			+ "reckless@_@sembrono, nekat@_@false@_@false@-@"
			+ "reckon@_@memperhitungkan, menggabungkan@_@true@_@false@-@"
			+ "recuperate@_@menguatkan diri kembali, sembuh@_@false@_@true@-@"
			+ "refer@_@menunjuk@_@false@_@true@-@"
			+ "refrigerator@_@kulkas@_@false@_@true@-@"
			+ "refuge@_@tempat perlindungan@_@false@_@true@-@"
			+ "regardless@_@tanpa menghiraukan@_@true@_@false@-@"
			+ "regiment@_@resimen, jumlah besar@_@false@_@false@-@"
			+ "regret@_@penyesalan@_@false@_@true@-@"
			+ "rehearsal@_@latihan, geladi@_@false@_@false@-@"
			+ "rehearse@_@berlatih@_@false@_@false@-@"
			+ "reign@_@kekuasaan, pemerintahan@_@true@_@false@-@"
			+ "reindeer@_@rusa kutub@_@false@_@true@-@"
			+ "relative@_@sanak pamili@_@false@_@true@-@"
			+ "reliable@_@dapat dipercaya, dapat diandalkan@_@false@_@true@-@"
			+ "reluctant@_@segan@_@true@_@false@-@"
			+ "rely@_@mempercayakan@_@false@_@true@-@"
			+ "remarkable@_@luarbiasa@_@false@_@false@-@"
			+ "rendezvous@_@pertemuan, tempat pertemuan@_@false@_@true@-@"
			+ "repel@_@menolak, memukul mundur@_@false@_@true@-@"
			+ "repent@_@bertobat, menyesal@_@true@_@false@-@"
			+ "repentance@_@penyesalan, tobat@_@true@_@false@-@"
			+ "replenish@_@melengkapi lagi@_@false@_@true@-@"
			+ "representative@_@wakil, bersifat mewakili@_@false@_@false@-@"
			+ "repulsive@_@menjijikan@_@true@_@false@-@"
			+ "resemble@_@menyerupai@_@false@_@false@-@"
			+ "resentment@_@kemarahan, kebencian@_@true@_@false@-@"
			+ "reserve@_@cadangan@_@true@_@false@-@"
			+ "reserved@_@pendiam, dipesan@_@false@_@true@-@"
			+ "resident@_@penduduk@_@false@_@true@-@"
			+ "resisting@_@menentang@_@false@_@true@-@"
			+ "resolve@_@memecahkan, memutuskan@_@true@_@false@-@"
			+ "restrain@_@mengendalikan@_@true@_@false@-@"
			+ "restraint@_@pengendalian@_@true@_@false@-@"
			+ "retaliate@_@membalas(dendam)@_@true@_@false@-@"
			+ "retreat@_@mundurnya@_@false@_@true@-@"
			+ "reveal@_@mengungkapkan@_@false@_@true@-@"
			+ "reverie@_@lamunan, angan-angan@_@true@_@false@-@"
			+ "reverse@_@kebalikan@_@false@_@false@-@"
			+ "revert@_@kembali pada@_@false@_@true@-@"
			+ "revoke@_@menjabut, menarik@_@false@_@true@-@"
			+ "revolt@_@pemberontakan@_@false@_@true@-@"
			+ "rib@_@tulang rusuk, iga@_@false@_@true@-@"
			+ "ribbon@_@pita mesin ketik@_@false@_@true@-@"
			+ "ricochet@_@memantul, pemantulan@_@false@_@false@-@"
			+ "rid@_@membersihkan, melemparkan@_@false@_@false@-@"
			+ "riddle@_@teka-teki@_@true@_@false@-@"
			+ "righteous@_@berbudi, budiman@_@false@_@false@-@"
			+ "rigid@_@kaku, keras@_@false@_@true@-@"
			+ "rigorous@_@keras, dengan teliti@_@true@_@false@-@"
			+ "riot@_@kerisauan@_@true@_@false@-@"
			+ "ripple@_@reaksi, suara@_@true@_@false@-@"
			+ "rogue@_@anak nakal@_@true@_@false@-@"
			+ "rot@_@kebusukan@_@false@_@true@-@"
			+ "rough@_@kasar@_@false@_@true@-@"
			+ "rowing@_@mengayuh@_@false@_@false@-@"
			+ "rubble@_@reruntuhan puing@_@true@_@false@-@"
			+ "ruckus@_@keributan, kehebohan@_@false@_@false@-@"
			+ "rudder@_@kemudi@_@false@_@false@-@"
			+ "rude@_@kasar, tdk sopan@_@false@_@true@-@"
			+ "ruffian@_@bajingan, bangsat@_@true@_@false@-@"
			+ "rug@_@permadani@_@true@_@false@-@"
			+ "ruin@_@reruntuhan, kejatuhan, menggagalkan@_@false@_@true@-@"
			+ "ruined@_@merusak@_@true@_@false@-@"
			+ "rumble@_@gemuruh@_@true@_@false@-@"
			+ "runt@_@yang kerdil@_@true@_@false@-@"
			+ "rustic@_@kedusunan(manner of speak)@_@true@_@false@-@"
			+ "ruthless@_@zalim, kejam, bengis@_@true@_@false@-@"
			+ "sake@_@demi, untuk kepentingan@_@false@_@true@-@"
			+ "salvage@_@tindakan penyelamatan@_@false@_@false@-@"
			+ "sanction@_@persetujuan@_@true@_@false@-@"
			+ "sanity@_@kesehatan jiwa@_@false@_@false@-@"
			+ "sate@_@mengenyangkan@_@true@_@false@-@"
			+ "savage@_@orang biadab@_@false@_@false@-@"
			+ "saviour@_@penyelamat@_@false@_@true@-@"
			+ "scalpel@_@pisau bedah@_@false@_@true@-@"
			+ "scant@_@sedikit, kurang, tak cukup@_@false@_@false@-@"
			+ "scatter@_@menyebar@_@false@_@false@-@"
			+ "scavenger@_@burung pemakan bangkai@_@false@_@false@-@"
			+ "scent@_@bau, penciuman@_@true@_@false@-@"
			+ "scold@_@memarahi, cercaan, hardikan@_@false@_@false@-@"
			+ "scorch@_@gosong, menghanguskan@_@true@_@false@-@"
			+ "scorn@_@caci-maki, cemoohan@_@true@_@false@-@"
			+ "scoundrel@_@brandal, bajingan@_@true@_@false@-@"
			+ "scrap@_@sisa, potongan@_@true@_@false@-@"
			+ "scribbled@_@tulisan cakar ayam@_@false@_@true@-@"
			+ "scrupulous@_@cermat, teliti, seksama@_@true@_@false@-@"
			+ "scrutinize@_@menyimak@_@true@_@false@-@"
			+ "sculpt@_@memahat, mengukir@_@false@_@false@-@"
			+ "scum@_@sampah@_@false@_@true@-@"
			+ "scythe@_@sabit besar@_@false@_@true@-@"
			+ "seal@_@menutup, mengunci, anjing laut@_@true@_@false@-@"
			+ "sedate@_@tenang, tidak ribut@_@true@_@false@-@"
			+ "seek@_@mencari@_@false@_@true@-@"
			+ "seems@_@rupa rupanya, kelihatannya@_@false@_@true@-@"
			+ "seize@_@meraih@_@true@_@false@-@"
			+ "selfishly@_@dg kepentingan sendiri@_@false@_@true@-@"
			+ "separate@_@berpisah@_@false@_@true@-@"
			+ "serenade@_@merayu dg musik@_@false@_@false@-@"
			+ "servant@_@pelayan@_@false@_@true@-@"
			+ "settle@_@menyudahi, memenangkan@_@false@_@true@-@"
			+ "severe@_@parah, berat, hebat@_@false@_@true@-@"
			+ "sewer@_@penjahit, got@_@false@_@true@-@"
			+ "shabby@_@jorok@_@false@_@false@-@"
			+ "shackle@_@belenggu@_@true@_@false@-@"
			+ "shaggy@_@berewok, berbulu kusut@_@true@_@false@-@"
			+ "shaky@_@gemetar, goyang, goyah@_@true@_@false@-@"
			+ "shambles@_@keadaan berantakan@_@false@_@false@-@"
			+ "shame@_@rasa malu@_@false@_@true@-@"
			+ "shameless@_@tak tahu malu@_@false@_@true@-@"
			+ "shatter@_@menghancurkan, pecahan@_@true@_@false@-@"
			+ "shave@_@mencukur@_@false@_@true@-@"
			+ "sheer@_@curam, terjal@_@true@_@false@-@"
			+ "shelf@_@rak@_@true@_@false@-@"
			+ "shelter@_@berlindung, perlindungan@_@true@_@false@-@"
			+ "shipwright@_@tukang kayu kapal@_@false@_@false@-@"
			+ "shiver@_@gemetar@_@false@_@true@-@"
			+ "shore@_@pantai, tepi laut@_@false@_@false@-@"
			+ "shove@_@mendorong, menggeser@_@true@_@false@-@"
			+ "shrimp@_@udang@_@false@_@false@-@"
			+ "shrine@_@tempat keramat@_@false@_@false@-@"
			+ "shroud@_@menyelimuti@_@true@_@false@-@"
			+ "silhouette@_@bayangan hitam@_@false@_@true@-@"
			+ "simpleton@_@orang yg tolol@_@true@_@false@-@"
			+ "simulate@_@menirukan@_@false@_@true@-@"
			+ "sin@_@dosa-dosa@_@false@_@true@-@"
			+ "sinister@_@seram, menakutkan@_@true@_@false@-@"
			+ "skirmish@_@pertempuran kecil@_@false@_@false@-@"
			+ "slaughter@_@menyembelih@_@false@_@true@-@"
			+ "slay@_@membunuh@_@false@_@true@-@"
			+ "slight@_@sedikit, mengabaikain@_@false@_@true@-@"
			+ "slipper@_@sandal@_@false@_@true@-@"
			+ "slit@_@membelah@_@true@_@false@-@"
			+ "slope@_@lereng@_@false@_@false@-@"
			+ "slovenly@_@jorok, ceroboh@_@true@_@false@-@"
			+ "slug@_@siput@_@false@_@true@-@"
			+ "slumber@_@tidur@_@false@_@false@-@"
			+ "sly@_@licik@_@false@_@true@-@"
			+ "smithereens@_@pecahan@_@false@_@false@-@"
			+ "smuggle@_@menyelundupkan@_@false@_@true@-@"
			+ "snare@_@jerat, perangkap@_@false@_@false@-@"
			+ "snatch@_@merenggut, menculik, merampas@_@true@_@false@-@"
			+ "sneak@_@pergi diam\"@_@true@_@false@-@"
			+ "snob@_@org yg suka membanggakan diri@_@false@_@false@-@"
			+ "snore@_@dengkur@_@true@_@false@-@"
			+ "snuck@_@menyelinap@_@false@_@true@-@"
			+ "soak@_@merendam, , membasahi (hingga basah kuyup)@_@false@_@true@-@"
			+ "sober@_@siuman@_@false@_@true@-@"
			+ "sole@_@tapak sepatu@_@false@_@true@-@"
			+ "solely@_@semata-mata@_@true@_@false@-@"
			+ "solemnly@_@dengan khidmat@_@false@_@false@-@"
			+ "sophistication@_@pengalaman dalam soal\" duniawi@_@true@_@false@-@"
			+ "sorrow@_@dukacita@_@true@_@false@-@"
			+ "southpaw@_@orang kidal@_@false@_@true@-@"
			+ "sovereignty@_@kedaulatan@_@false@_@false@-@"
			+ "spade@_@sekop@_@false@_@true@-@"
			+ "specimen@_@bahan percobaan@_@false@_@true@-@"
			+ "spectacle@_@tontonan@_@false@_@true@-@"
			+ "spell@_@ejaan@_@false@_@false@-@"
			+ "spew@_@memuntahkan @_@false@_@true@-@"
			+ "spike@_@paku@_@false@_@true@-@"
			+ "spine@_@tulang belakang@_@false@_@true@-@"
			+ "spite@_@dengki, dendam, irihati@_@false@_@false@-@"
			+ "spouse@_@suami, isteri@_@false@_@true@-@"
			+ "spur@_@memacu@_@false@_@true@-@"
			+ "squeeze@_@memeras(uang)@_@false@_@false@-@"
			+ "stab@_@menikam@_@false@_@true@-@"
			+ "stain@_@noda@_@false@_@true@-@"
			+ "stake@_@mempertaruhkan@_@true@_@false@-@"
			+ "stalk@_@mengejar, batang, tangkai, @_@false@_@true@-@"
			+ "stash@_@menyembunyikan(food/money)@_@true@_@false@-@"
			+ "stature@_@tinggi seseorang, struktur badan@_@false@_@true@-@"
			+ "steer@_@mengemudikan@_@false@_@false@-@"
			+ "stench@_@bau busuk/amis@_@false@_@false@-@"
			+ "stew@_@rebusan@_@false@_@false@-@"
			+ "stiff@_@kaku@_@true@_@true@-@"
			+ "stiffen@_@mengeras@_@false@_@true@-@"
			+ "stilt@_@jangkauan@_@false@_@false@-@"
			+ "stink@_@bau busuk@_@false@_@true@-@"
			+ "stir@_@kegemparn@_@true@_@false@-@"
			+ "stitch@_@jahitan@_@true@_@false@-@"
			+ "strain@_@ketegangan@_@true@_@false@-@"
			+ "stranded@_@terdampar@_@true@_@false@-@"
			+ "strangle@_@mencekik@_@false@_@false@-@"
			+ "stretch@_@merentangkan@_@false@_@true@-@"
			+ "strict@_@keras(disiplin)@_@true@_@false@-@"
			+ "strife@_@perselisihan, percekcokan@_@true@_@false@-@"
			+ "strive@_@berusaha/bekerja keras@_@true@_@false@-@"
			+ "striving@_@bekerja keras@_@false@_@true@-@"
			+ "struggle@_@berjuang@_@false@_@false@-@"
			+ "stubborn@_@keras kepala@_@false@_@true@-@"
			+ "stunt@_@pertunjukan ketangkasan@_@false@_@true@-@"
			+ "sturdy@_@kokoh, kuat, kekar@_@false@_@false@-@"
			+ "succeeded@_@berhasil@_@false@_@true@-@"
			+ "sue@_@menggugat, menuntut@_@false@_@true@-@"
			+ "suffice@_@mencukupi@_@true@_@false@-@"
			+ "suffocate@_@mencekik, mati lemas@_@true@_@false@-@"
			+ "suicide@_@bunuh diri@_@false@_@true@-@"
			+ "sulk@_@merajuk, mendongkol@_@true@_@false@-@"
			+ "summit@_@puncak, konferensi tingat tinggi@_@false@_@true@-@"
			+ "superimpose@_@menempatkan diatas@_@false@_@false@-@"
			+ "superintendent@_@pengawas@_@false@_@true@-@"
			+ "suppose@_@mengharuskan, mengira, , seandainya@_@false@_@false@-@"
			+ "supreme@_@tertinggi, unggul, terpenting@_@false@_@true@-@"
			+ "surge@_@gelora, menggelora, gelombang besar, bergelombang@_@false@_@false@-@"
			+ "surgery@_@operasi, pembedahan@_@false@_@true@-@"
			+ "surpassing@_@melebihi, melampaui, mengungguli@_@false@_@true@-@"
			+ "surveillance@_@pengawasan@_@false@_@true@-@"
			+ "survival@_@kelangsungan hidup@_@false@_@true@-@"
			+ "survivor@_@orang yg selamat@_@false@_@true@-@"
			+ "suspicious@_@curiga@_@false@_@true@-@"
			+ "sustain@_@menopang@_@false@_@false@-@"
			+ "swallow@_@burung layang-layang, menelan@_@false@_@true@-@"
			+ "swamp@_@rawa@_@false@_@false@-@"
			+ "sway@_@goyangan@_@true@_@false@-@"
			+ "swerve@_@membelokan, mengelak, pembelokan@_@false@_@false@-@"
			+ "swindle@_@penipuan, pengecohan@_@false@_@false@-@"
			+ "syllables@_@suku kata@_@false@_@false@-@"
			+ "symptom@_@gejala@_@false@_@false@-@"
			+ "tact@_@kebijaksanaan@_@true@_@false@-@"
			+ "taint@_@noda@_@false@_@false@-@"
			+ "tangible@_@nyata@_@false@_@false@-@"
			+ "tangle@_@menjerat@_@true@_@false@-@"
			+ "tantamount@_@serupa, sama@_@true@_@false@-@"
			+ "tarnish@_@menodai@_@false@_@false@-@"
			+ "tasty@_@enak, lezat, gurih@_@false@_@true@-@"
			+ "taught@_@teach@_@false@_@true@-@"
			+ "tease@_@menggoda@_@false@_@false@-@"
			+ "temper@_@sifat, watak@_@false@_@true@-@"
			+ "tenacity@_@ketahanan, kegigihan@_@true@_@false@-@"
			+ "tend@_@merawat, memelihara, cenderung@_@false@_@false@-@"
			+ "tender@_@empuk, lembut, lunak@_@true@_@false@-@"
			+ "terrify@_@menakutkan, mengerikan@_@false@_@true@-@"
			+ "testament@_@wasiat@_@false@_@false@-@"
			+ "thaw@_@cair@_@true@_@false@-@"
			+ "therefore@_@oleh karena itu@_@false@_@true@-@"
			+ "thick@_@tebal@_@false@_@true@-@"
			+ "thirst@_@dahaga, kehausan@_@false@_@true@-@"
			+ "though@_@lebih dulu, meskipun, walaupun, bagaimanapun juga@_@false@_@false@-@"
			+ "thought@_@think@_@false@_@true@-@"
			+ "threat@_@ancaman@_@false@_@true@-@"
			+ "thrill@_@getaran hati@_@false@_@true@-@"
			+ "throat@_@tenggorokan@_@false@_@true@-@"
			+ "throne@_@takhta, singgasana@_@false@_@false@-@"
			+ "through@_@melalui, melewati, sampai, , sepanjang, seluruh@_@false@_@true@-@"
			+ "thud@_@gedebuk(fallen body)@_@false@_@true@-@"
			+ "tissue@_@jaringan otot, kertas tisu@_@false@_@true@-@"
			+ "toe@_@jari kaki@_@false@_@true@-@"
			+ "tombstone@_@batu nisan@_@false@_@false@-@"
			+ "took@_@take@_@false@_@true@-@"
			+ "torment@_@menyiksa@_@false@_@false@-@"
			+ "torrent@_@aliran air yg deras@_@false@_@true@-@"
			+ "torso@_@batang tubuh@_@false@_@false@-@"
			+ "torture@_@siksaan@_@false@_@false@-@"
			+ "tough@_@keras, kuat, buruk, kasar, berat@_@true@_@false@-@"
			+ "towel@_@handuk@_@false@_@true@-@"
			+ "trample@_@menginjak-injak@_@true@_@false@-@"
			+ "tranquilize@_@menenangkan@_@false@_@true@-@"
			+ "treat@_@memperlakukan, sesuatu yg menyenangkan@_@false@_@true@-@"
			+ "tremble@_@menggigil, gemetar@_@true@_@false@-@"
			+ "trench@_@parit perlindungan@_@true@_@false@-@"
			+ "trial@_@pemeriksaan pengadilan, , percobaan@_@false@_@false@-@"
			+ "tribute@_@upeti, penghargaan@_@true@_@false@-@"
			+ "trident@_@trisula@_@false@_@true@-@"
			+ "trinket@_@perhiasan kecil@_@false@_@true@-@"
			+ "triumph@_@kemenangan@_@false@_@false@-@"
			+ "trivial@_@sepele, remeh temeh@_@false@_@false@-@"
			+ "trout@_@ikan air tawar@_@false@_@false@-@"
			+ "truly@_@sunguh-sunguh, betul-betul@_@true@_@false@-@"
			+ "tug@_@sentakan@_@true@_@false@-@"
			+ "tumult@_@kegemparan, keributan@_@true@_@false@-@"
			+ "turf@_@tanah berumput@_@true@_@false@-@"
			+ "turmoil@_@huru hara@_@false@_@true@-@"
			+ "tycoon@_@hartawan, raja@_@true@_@false@-@"
			+ "undeniable@_@tak dapat di sangkal/dibantah@_@false@_@false@-@"
			+ "upheaval@_@kehebohan@_@false@_@false@-@"
			+ "urchin@_@anat melarat, anak miskin@_@false@_@false@-@"
			+ "urge@_@mendesak, dorongan@_@false@_@true@-@"
			+ "utter@_@samasekali@_@false@_@true@-@"
			+ "utterly@_@sepenuhnya@_@false@_@false@-@"
			+ "vague@_@samar-samar, tidak jelas@_@true@_@false@-@"
			+ "vain@_@dg sia sia@_@false@_@true@-@"
			+ "vanguard@_@barisan depan@_@false@_@true@-@"
			+ "vanish@_@lenyap, menghilang@_@false@_@true@-@"
			+ "vast@_@luas@_@false@_@true@-@"
			+ "vault@_@ruangan besi, kubah@_@false@_@false@-@"
			+ "veil@_@selubung, diselubungi@_@true@_@false@-@"
			+ "vein@_@urat darah@_@false@_@false@-@"
			+ "ventriloquists@_@ahli bicara perut@_@false@_@false@-@"
			+ "venture@_@usaha berbahaya@_@true@_@false@-@"
			+ "verdict@_@putusan@_@false@_@true@-@"
			+ "verge@_@ambang batas@_@false@_@false@-@"
			+ "veritable@_@benar-benar@_@false@_@false@-@"
			+ "versatile@_@cakap dalam berbagai hal@_@true@_@false@-@"
			+ "vessel@_@kapal@_@true@_@false@-@"
			+ "vicinity@_@sekitar@_@false@_@true@-@"
			+ "vicious@_@jahat, buruk@_@true@_@false@-@"
			+ "victim@_@korban@_@false@_@true@-@"
			+ "vigor@_@kekuatan, tenaga, kegiatan@_@false@_@false@-@"
			+ "vigorous@_@giat, penuh semangat@_@false@_@true@-@"
			+ "vigour@_@tenaga@_@false@_@false@-@"
			+ "vile@_@busuk, kotor@_@false@_@false@-@"
			+ "vine@_@tumbuh-tumbuhan merambat@_@false@_@true@-@"
			+ "violinist@_@pemain biola@_@false@_@true@-@"
			+ "vitality@_@daya hidup@_@false@_@false@-@"
			+ "vouch@_@menjamin @_@true@_@false@-@"
			+ "vow@_@bersumpah, sumpah@_@false@_@true@-@"
			+ "vowel@_@huruf hidup, vocal@_@true@_@false@-@"
			+ "voyage@_@pelayaran, perjalanan@_@true@_@false@-@"
			+ "vulnerable@_@yg mudah diserang@_@false@_@false@-@"
			+ "waist@_@pinggang@_@false@_@false@-@"
			+ "walnut@_@kenari@_@true@_@false@-@"
			+ "wander@_@menyeluyur, mengembara@_@false@_@true@-@"
			+ "wealth@_@kekayaan@_@false@_@true@-@"
			+ "weed@_@rumput liar@_@false@_@false@-@"
			+ "wench@_@gadis, dara@_@true@_@false@-@"
			+ "whether@_@apakah@_@false@_@true@-@"
			+ "whine@_@merengek@_@true@_@false@-@"
			+ "whip@_@cemeti, cambuk@_@false@_@true@-@"
			+ "wield@_@memegang dan menggunakan@_@false@_@true@-@"
			+ "willing@_@rela@_@false@_@true@-@"
			+ "wimp@_@pengecut@_@false@_@false@-@"
			+ "wink@_@kedipan@_@false@_@true@-@"
			+ "wipe@_@menghapus, menyapu, membersihkan@_@false@_@true@-@"
			+ "witch@_@tukang sihir wanita@_@false@_@true@-@"
			+ "wither@_@lemah, layu@_@true@_@false@-@"
			+ "wobbly@_@goyah, goyang@_@false@_@true@-@"
			+ "wonder@_@bertanya-tanya, heran@_@false@_@true@-@"
			+ "worst@_@yang paling buruk@_@false@_@true@-@"
			+ "wrack@_@bobrok@_@false@_@false@-@"
			+ "wrap@_@bungkus@_@false@_@true@-@"
			+ "wrath@_@kegusaran, kemarahan, kemurakaan@_@true@_@false@-@"
			+ "wreck@_@menghancurkan, merusak@_@false@_@false@-@"
			+ "wretched@_@tidak enak badan@_@true@_@false@-@"
			+ "wrist@_@pergelangan tangan@_@false@_@true@-@"
			+ "youth@_@masa muda@_@false@_@true@-@" + "";

}
